# Generated by Django 5.0.3 on 2024-12-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='rims',
            field=models.ManyToManyField(to='blog.rims'),
        ),
        migrations.AddField(
            model_name='order',
            name='spares',
            field=models.ManyToManyField(to='blog.spares'),
        ),
    ]
